# Generated by Django 4.1.3 on 2022-11-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('dateandtime', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=5)),
                ('assets', models.IntegerField()),
            ],
        ),
    ]
