# Generated by Django 4.1.3 on 2022-11-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('dateandtime', models.CharField(max_length=50)),
                ('assets', models.IntegerField()),
                ('asset_type', models.CharField(max_length=20)),
                ('asset_sensitivity', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('applied', models.CharField(default='Not Applied', max_length=20)),
            ],
        ),
    ]
